[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "project_folder/WhenCanYouHangOut"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# API proxy for development/testing
[[redirects]]
  from = "/api/*"
  to = "https://your-actual-railway-backend-url.up.railway.app/api/:splat"
  status = 200
  force = true
