[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "project_folder/WhenCanYouHangOut"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# API proxy (only used if frontend makes relative /api calls; safe with VITE_API_URL)
[[redirects]]
  from = "/api/*"
  to = "https://wcyho-backend.onrender.com/:splat"
  status = 200
  force = true
