services:
  - type: web
    name: wcyho-backend
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://wcyho.netlify.app
